# Generated by Django 4.2 on 2023-04-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0002_link_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='identifier',
        ),
    ]
