# Generated by Django 4.2 on 2023-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0003_remove_link_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
