# Generated by Django 4.2 on 2023-05-01 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0006_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=5, unique=True),
        ),
    ]
